ruleDirs:
  - ./rules
testConfigs:
  - testDir: ./rule-tests

customLanguages:
  spicy:
    libraryPath: node_modules/tree-sitter-spicy/build/Release/tree_sitter_spicy_binding.node
    extensions: [spicy]
