name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm test

  pre-commit:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
